services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: goserver
    container_name: goserver_api
    restart: unless-stopped
    env_file: .env
    ports:
      - '${SERVER_PORT}:8080'
    depends_on:
      - postgres
      - redis
      - migrate

  postgres:
    image: postgres:18.1
    container_name: goserver_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - dbdata:/data/db
      # optional pgseed scripts
      - ./.extra/setup/pgseed.sql:/docker-entrypoint-initdb.d/pgseed.sql:ro
  
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    entrypoint: ["migrate"]

  redis:
    image: redis:8.4.0
    container_name: goserver_redis
    restart: unless-stopped
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --bind localhost --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data/cache

volumes:
  dbdata:
  cache:
    driver: local